name: harutodo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # 상태 관리
  provider: ^6.1.2
  
  # 로컬 데이터베이스
  sqflite: ^2.4.1
  path: ^1.8.3
  
  # 날짜/시간 처리
  intl: ^0.20.2
  
  # 파일 경로
  path_provider: ^2.1.1

  # 캘린더 위젯
  table_calendar: ^3.1.2

  # 애니메이션
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2

  flutter_native_splash: ^2.3.13
  
  # 라우팅
  go_router: ^14.6.2
  
  # 앱 정보
  package_info_plus: ^8.3.0
  
  # HTTP 요청
  http: ^1.4.0 # HTTP 요청을 보내는 패키지

  flutter_dotenv: ^5.2.1 # .env 파일에서 환경 변수를 로드하는 패키지

  # 로컬 알림
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/splash12.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/icons/splash12.png"
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - .env